//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6PracticeWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosistionList
    {
        public int Id { get; set; }
        public int PostId { get; set; }
        public int Quantity { get; set; }
        public int StaffingTableId { get; set; }
    
        public virtual Post Post { get; set; }
        public virtual StaffingTable StaffingTable { get; set; }
    }
}
