//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _6PracticeWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkingPeriod
    {
        public int Id { get; set; }
        public int DivisionID { get; set; }
        public int PostId { get; set; }
        public int Discharge { get; set; }
        public System.DateTime StartDate { get; set; }
        public int WorkerId { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    
        public virtual Division Division { get; set; }
        public virtual Post Post { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
